-- USANDO O BANCO DE DADOS MERCADO
USE streaming;

-- RESETANDO MAIS FÁCIL AS FUNÇÕES
SET FOREIGN_KEY_CHECKS = 0;

DELETE FROM usuario;
DELETE FROM planos;
DELETE FROM conteudo;
DELETE FROM assinatura;
DELETE FROM visualizacao;

ALTER TABLE usuario AUTO_INCREMENT = 1;
ALTER TABLE planos AUTO_INCREMENT = 1;
ALTER TABLE conteudo AUTO_INCREMENT = 1;
ALTER TABLE assinatura AUTO_INCREMENT = 1;
ALTER TABLE visualizacao AUTO_INCREMENT = 1;

SET FOREIGN_KEY_CHECKS = 1;